basePath: /
definitions:
  domain.Song:
    properties:
      group:
        type: string
      link:
        type: string
      release_date:
        type: string
      song:
        type: string
      text:
        type: string
    type: object
  server.groupRename:
    properties:
      new_name:
        type: string
      old_name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for songLibrary application
  title: mobileSongLibrary
  version: 1.0.0
paths:
  /library:
    get:
      description: Возвращает список всех песен с возможностью фильтрации через заголовки
      parameters:
      - description: Название группы
        in: header
        name: group
        type: string
      - description: Название песни
        in: header
        name: song
        type: string
      - description: Часть текста песни
        in: header
        name: text
        type: string
      - description: Ссылка на песню
        in: header
        name: link
        type: string
      - description: Дата релиза в формате 16.07.2006
        in: header
        name: release_date
        type: string
      - description: Лимит выдачи
        in: header
        name: limit
        type: integer
      - description: Смещение выдачи
        in: header
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Song'
            type: array
        "400":
          description: Некорректный запрос
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Получить всю библиотеку песен
      tags:
      - Library
  /renamegroup:
    patch:
      consumes:
      - application/json
      description: Изменяет название музыкальной группы
      parameters:
      - description: Старое и новое название группы
        in: body
        name: groupRename
        required: true
        schema:
          $ref: '#/definitions/server.groupRename'
      produces:
      - application/json
      responses:
        "204":
          description: Группа успешно переименована
          schema:
            type: string
        "400":
          description: Некорректный запрос
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Переименовать группу
      tags:
      - Groups
  /song:
    delete:
      consumes:
      - application/json
      description: Удаляет песню по названию и группе
      parameters:
      - description: Название группы и песни для удаления
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/domain.Song'
      produces:
      - application/json
      responses:
        "200":
          description: Успешное удаление
          schema:
            type: string
        "400":
          description: Некорректный запрос
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Удалить песню
      tags:
      - Songs
    get:
      description: Возвращает данные о песне с пагинацией текста
      parameters:
      - description: Название группы
        in: header
        name: group
        required: true
        type: string
      - description: Название песни
        in: header
        name: song
        required: true
        type: string
      - description: Номер страницы (по умолчанию 1)
        in: header
        name: page
        type: integer
      - description: Количество куплетов на странице (по умолчанию 2)
        in: header
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Некорректный запрос
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Получить информацию о песне
      tags:
      - Songs
    patch:
      consumes:
      - application/json
      description: Обновляет данные о песне, кроме её названия
      parameters:
      - description: Обновлённые данные песни
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/domain.Song'
      produces:
      - application/json
      responses:
        "200":
          description: Песня успешно обновлена
          schema:
            type: string
        "400":
          description: Некорректный запрос
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Обновить информацию о песне
      tags:
      - Songs
    post:
      consumes:
      - application/json
      description: Добавляет новую песню в библиотеку
      parameters:
      - description: Данные новой песни
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/domain.Song'
      produces:
      - application/json
      responses:
        "201":
          description: Песня успешно добавлена
          schema:
            type: string
        "400":
          description: Некорректный запрос
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Добавить новую песню
      tags:
      - Songs
swagger: "2.0"
